#%RAML 1.0 NamedExample

transactionId: "491e23ae-ji2l-496d-b05a-575d7db3c358"
APIName: "ei-sapi-fx-trate"
status: 504
message: "Gateway Timeout"
timeStamp: "2019-06-17T18:03:28.951-05:00"
errorType: "APIKIT:BAD_REQUEST"