#%RAML 1.0 DataType
type: object
description: collection of links that can be used for further navigation.
properties: 
    nextPageURL: 
      type: string
      required: false
    previousPageURL:
      type: string
      required: false
    currentPageURL:
      type: string
      required: false
    firstPageURL:
      type: string
      required: false
    lastPageURL:
      type: string
      required: false