#%RAML 1.0 NamedExample
totalSize: 40
links: 
 nextPageURL: /fxRates?pageToken=A7DxJ1Jl0JDKLS=&limit=100
fxRates: 
 - 
  currencyFrom: USD
  currencyTo: ARS
  conversionRate: 38.745
  conversionRateType: Corporate
  conversionDate: "2019-02-28"
 - 
  currencyFrom: USD
  currencyTo: INR
  conversionRate: 60.35
  conversionRateType: Corporate
  conversionDate: "2019-02-28"
 - 
  currencyFrom: USD
  currencyTo: SEK
  conversionRate: 9.20296289473684210526315789473684210526
  conversionRateType: Corporate
  conversionDate: "2019-02-28"
 - 
  currencyFrom: USD
  currencyTo: SGD
  conversionRate: 1.35492305263157894736842105263157894737
  conversionRateType: Corporate
  conversionDate: "2019-02-28"
 - 
  currencyFrom: USD
  currencyTo: SVC
  conversionRate: 8.75
  conversionRateType: Corporate
  conversionDate: "2019-02-28"